apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups: 
  - system:authenticated 
  request: $(cat server.csr | base64 | tr -d '\n')OR ENCRYPTED .csr with cat file.csr |base64
  usages:
  - digital signature
  - key encipherment
  - server auth