apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-vol1
spec:
 accessModes:
  - ReadWriteOnce/ReadOnlyMany/ReadWriteMany/
 capacity:
  storage: 1Gi
 hostPath:
  path: /tmp/data
 awsElasticBlockStore:
  volumeID: |volumeid|
  fsType: ext4