apiVersion: v1
kind: Pod
metadata:
 name: ubuntu-sleeper-pod
spec:
 containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep2.0"]    =  DOCKERFILE ENTRYPOINT
    args: ["10"]   = DOCKERFILE CMD
    env:
     - name: APP_COLOR
       value: pink   = Plain Key Value
OR
    env:
     - name: APP_COLOR
       valueFrom:
        configMapKeyRef:   =ConfigMap
OR
    env:
     - name: APP_COLOR
       valueFrom:
        secretKeyRef    = Secrets