apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user
spec:
  groups: 
  - system:authenticated 
  request: $(cat server.csr | base64 | tr -d '\n')OR ENCRYPTED .csr with LS0t... blabla bla
  usages:
  - digital signature
  - key encipherment
  - server auth